//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMS.Models.Vendors
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Vendor
    {
        public int Vid { get; set; }
        [Required(ErrorMessage = "Name is Required")]
        public string Vendor_Name { get; set; }
        [Required(ErrorMessage = "Contact is Required")]
        public string Vendor_Contact { get; set; }
        [Required(ErrorMessage = "Cnic is Required")]
        public string Vendor_Cnic { get; set; }
        [Required(ErrorMessage = "Gender is Required")]
        public string Vendor_Gender { get; set; }
        [Required(ErrorMessage = "Email is Required")]
        public string Vendor_Email { get; set; }
        [Required(ErrorMessage = "Address is Required")]
        public string Vendor_Shop_Address { get; set; }

    }
}
