//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMS.Models.Orders
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Order
    {
        public int Order_id { get; set; }
        [Required(ErrorMessage = "Product is Required")]
        public Nullable<int> Product_id { get; set; }
        public Nullable<int> Emp_id { get; set; }
        public Nullable<int> Branch_id { get; set; }
        [Required(ErrorMessage = "Quantity is Required")]
        public Nullable<int> Qty { get; set; }
    
        public string Product_Name { get; set; }
        public string Emp_Name { get; set; }
        public string Branch_Name { get; set; }
        public virtual Branches Branch { get; set; }
        public virtual Employees Employee { get; set; }
        public virtual Products Product { get; set; }
    }
}
