//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMS.Models.Branches
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Branch
    {
        public int Bid { get; set; }

        [Required(ErrorMessage = "Name is Required")]
        public string Branch_Name { get; set; }
        [Required(ErrorMessage = "Type is Required")]
        public string Branch_Type { get; set; }
        [Required(ErrorMessage = "Contact is Required")]
        public string Branch_Contact { get; set; }
        [Required(ErrorMessage = "Address is Required")]
        public string Branch_Address { get; set; }
        [Required(ErrorMessage = "City is Required")]
        public Nullable<int> City_id { get; set; }
        [Required(ErrorMessage = "Country is Required")]
        public Nullable<int> Country_id { get; set; }
    
        public string CItyName { get; set; }
        public string CountryName { get; set; }
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
    }
}
