//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    using System.Data.SqlClient;

    public class Login
    {
        public int Lid { get; set; }
        [DisplayName("UserName")]
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage ="UserName is Required")]
        public string email { get; set; }
        [DisplayName("Password")]
        [Required(ErrorMessage = "Password is Required")]
        [DataType(DataType.Password)]
        public string password { get; set; }
        public Nullable<int> Branch_id { get; set; }

        public static string GetBranchName(int bid)
        {
            Connection con = new Connection();
            con.getConnection();
            string BranchName = "";
            SqlCommand com = new SqlCommand("Select Branch_Name from Branch where Bid ='" + bid + "'", con.getConnection());
            SqlDataReader rd = com.ExecuteReader();
            while (rd.Read())
            {
                BranchName = rd["Branch_Name"].ToString();
            }
            return BranchName;
        }

    }
}
